project:
  type: website
  resources: assets

website:
  title: "Oliver Daboo"
  navbar:
    background: "#DA020E"
    logo: assets/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: Blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - text: Resume
        href: assets/Resume_Oliver Daboo.pdf
        target: blank
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ojdabo27/
        target: blank
      - icon: github
        href: https://github.com/oliverdaboo
        target: blank 
  page-footer: "© 2025 Oliver Daboo · Built with [Quarto](https://quarto.org)"
      
format:
  html:
    theme: 
      light: custom-light.scss
    css: styles.css
    toc: true
    
execute: 
  freeze: auto



